name: push-annotations
description: Push annotations from given file to GitHub repository.
runs:
  using: node16
  main: ./dist/index.js
inputs:
  annotations-file:
    description: Path to JSON file with annotations.
    required: true
  title:
    description: Title of the check.
    required: false
